#!/usr/bin/env bash

# Load the Nix environment through direnv
eval "$(direnv export bash)"

# Now run your checks in the Nix environment
. "$(dirname -- "$0")/_/husky.sh"

# Generate Supabase types
bun types:gen

# Run type check
bun tsc --noEmit

# Run linting
bun lint

# Run formatting
bun format
nixfmt flake.nix

# Run build
bun run build

# Run tests
bun test

# Stage formatting changes
git add -u
