#!/usr/bin/env bash

# Load the Devbox environment through direnv
eval "$(devbox generate direnv --print-envrc)"

# Now run your checks in the Devbox environment
. "$(dirname -- "$0")/_/husky.sh"

# Generate Supabase types
bun types

# Run linting
bun lint

# Run formatting
bun format
nixfmt flake.nix

# Run type check
bun tsc --noEmit

# Run build
bun run build

# Run tests
bun test

# Stage formatting changes
git add -u
