name: CI/CD

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  pull_request:
  merge_group:

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jetify-com/devbox-install-action@v0.12.0
        with:
          enable-cache: true

      - name: Setup environment
        run: |
          mkdir -p .devbox/gen/flake/glibc-patch
          echo "glibc-patch.url=\"path:$GITHUB_WORKSPACE/.devbox/gen/flake/glibc-patch\"" > .devbox/gen/flake/flake.nix

      - name: Install dependencies
        run: |
          devbox install
          devbox run prepare

      - name: Link Vercel Project
        run: pnpm exec vercel link --yes --project ${{ env.VERCEL_PROJECT_ID }} --token=${{ secrets.VERCEL_TOKEN }}

      - name: Pull Preview Environment Variables
        run: pnpm exec vercel env pull .env --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Link Supabase
        run: pnpm exec supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }} --password ${{ secrets.SUPABASE_DB_PASSWORD }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_TOKEN }}

      - name: Check Database Changes
        run: pnpm exec supabase db push --dry-run --password ${{ secrets.SUPABASE_DB_PASSWORD }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_TOKEN }}

      - name: Deploy Preview to Vercel
        if: github.event_name == 'pull_request'
        run: pnpm exec vercel deploy --token=${{ secrets.VERCEL_TOKEN }}

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' || github.event_name == 'merge_group') && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - uses: jetify-com/devbox-install-action@v0.12.0
        with:
          enable-cache: true

      - name: Setup environment
        run: |
          mkdir -p .devbox/gen/flake/glibc-patch
          echo "glibc-patch.url=\"path:$GITHUB_WORKSPACE/.devbox/gen/flake/glibc-patch\"" > .devbox/gen/flake/flake.nix

      - name: Install dependencies
        run: |
          devbox install
          devbox run prepare

      - name: Link Vercel Project
        run: pnpm exec vercel link --yes --project ${{ env.VERCEL_PROJECT_ID }} --token=${{ secrets.VERCEL_TOKEN }}

      - name: Pull Preview Environment Variables
        run: pnpm exec vercel env pull .env --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Link Supabase
        run: pnpm exec supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }} --password ${{ secrets.SUPABASE_DB_PASSWORD }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_TOKEN }}

      - name: Deploy Database Changes
        run: pnpm exec supabase db push --password ${{ secrets.SUPABASE_DB_PASSWORD }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_TOKEN }}

      - name: Deploy Edge Functions
        run: pnpm exec supabase functions deploy
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_TOKEN }}

      - name: Deploy to Vercel
        run: pnpm exec vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
