name: CI/CD

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:
  merge_group:

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install Devbox
      - name: Install Devbox
        uses: jetify-com/devbox-install-action@latest
        with:
          enable-cache: 'true'

      - name: Install Dependencies
        run: devbox run install

      - name: Link Vercel Project
        run: devbox run vercel link --yes --project ${{ env.VERCEL_PROJECT_ID }} --token=${{ secrets.VERCEL_TOKEN }}

      - name: Pull Preview Environment Variables
        run: devbox run vercel env pull .env --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Run Supabase
        run: devbox run supabase
        env:
          DOCKER_CLIENT_TIMEOUT: 120
          COMPOSE_HTTP_TIMEOUT: 120

      - name: Link Supabase
        run: devbox run supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }} --password ${{ secrets.SUPABASE_DB_PASSWORD }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_TOKEN }}

      - name: Check Database Changes
        run: devbox run supabase db push --dry-run --password ${{ secrets.SUPABASE_DB_PASSWORD }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_TOKEN }}

      - name: Run Build
        run: devbox run build

      - name: Run Test
        run: devbox run test
        env:
          SUPABASE_URL: http://localhost:54321
          SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0

      - name: Deploy Preview to Vercel
        if: github.event_name == 'pull_request'
        run: devbox run vercel deploy --token=${{ secrets.VERCEL_TOKEN }}

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' || github.event_name == 'merge_group') && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      # Install Devbox
      - name: Install Devbox
        uses: jetify-com/devbox-install-action@v0.12.0
        with:
          enable-cache: 'true'

      - name: Install Dependencies
        run: |
          devbox services stop
          devbox run install

      - name: Run Build
        run: devbox run build

      - name: Link Vercel Project
        run: devbox run vercel link --yes --project ${{ env.VERCEL_PROJECT_ID }} --token=${{ secrets.VERCEL_TOKEN }}

      - name: Pull Preview Environment Variables
        run: devbox run vercel env pull .env --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Run Supabase
        run: devbox run supabase
        env:
          DOCKER_CLIENT_TIMEOUT: 120
          COMPOSE_HTTP_TIMEOUT: 120

      - name: Link Supabase
        run: devbox run supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }} --password ${{ secrets.SUPABASE_DB_PASSWORD }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_TOKEN }}

      - name: Deploy Database Changes
        run: devbox run supabase db push --password ${{ secrets.SUPABASE_DB_PASSWORD }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_TOKEN }}

      - name: Deploy Edge Functions
        run: devbox run supabase functions deploy
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_TOKEN }}

      - name: Deploy to Vercel
        run: devbox run vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
